# Generated by Django 5.0.6 on 2024-05-12 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Enter name for the course ')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('video', models.TextField(default='http://youtube.com')),
                ('assignedCourse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lge.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Queistion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('queistion', models.TextField(help_text='Enter a question')),
                ('option1', models.CharField()),
                ('option2', models.CharField()),
                ('option3', models.CharField()),
                ('rightAnswear', models.CharField()),
                ('assignedToLesson', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lge.lesson')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(unique=True)),
                ('assignedToCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lge.course')),
            ],
        ),
    ]
